# Set the default terminal mode to 256color mode
# set -g default-terminal "screen-256color"

############################################################
#
# GENERAL
#
############################################################

# Start numbering at 1
set -g base-index 1

# Allows for faster key repetition
set -s escape-time 0

############################################################
#
# KEY BINDINGS
#
############################################################

# Use C-a instead of C-b
set -g prefix C-a
bind-key C-a last-window

setw -g mode-keys vi

# reload config file
bind r source-file ~/.tmux.conf

setw -g monitor-activity on
set -g visual-activity on

# Set mouse mode on
set -g mouse on
