tmux:
  symbols:
    branch: " "
    hashprefix: ":"
    ahead: "↑"
    behind: "↓"
    staged: "+"
    conflict: "!"
    modified: "~"
    untracked: "?"
    stashed: "*"
    clean: ""
    insertions: "+"
    deletions: "-"
  styles:
    clear: "#[fg=default]"
    state: "#[fg=red,bold]"
    branch: "#[fg=#89b4fa]"
    remote: "#[fg=#cba6f7]"
    divergence: "#[fg=#f9e2af]"
    staged: "#[fg=#a6e3a1]"
    conflict: "#[fg=#f38ba8]"
    modified: "#[fg=#f9e2af]"
    untracked: "#[fg=#89dceb]"
    stashed: "#[fg=#fab387]"
    clean: "#[fg=#a6e3a1]"
    insertions: "#[fg=#a6e3a1]"
    deletions: "#[fg=#f38ba8]"
  layout:
    - branch
    - " .."
    - remote
    - divergence
    - " - "
    - flags
  options:
    branch_max_len: 30
    branch_trim: right
    hide_clean: true
